#!/bin/bash
# This script starts AMPL on PrecisionFDA (pFDA). It comes preloaded onto the snapshot so that it can be run by typing `./start`
# Note: This file is re-named to `start` inside the pFDA Snapshot.
# This remains `start_pfda` to avoid ambiguoity between starting AMPL vs starting AMPL on pFDA
set -ex

HOST=$DX_JOB_ID.dnanexus.cloud

# Git repo
AMPL_DIR=AMPL/
if [ -d $AMPL_DIR ];
then
  rm -rf $AMPL_DIR
fi
git clone https://github.com/mass-matrix/AMPL
cd $AMPL_DIR

# Get config file
yes | pfda download .env || true
. .env

# Docker
pfda download "ampl-${PLATFORM}-${ENV}.tar.gz" -space-id 719
make load-docker
make jupyter-notebook host=$HOST
